M48
; DRILL file {KiCad 6.0.9-8da3e8f707~117~ubuntu22.04.1} date Tue 29 Nov 2022 09:47:10 AM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-29T09:47:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~117~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.9Y-2.675
X5.9Y-4.0
T0
M30
